name: Generate Database Documentation
on:
  workflow_dispatch:
    inputs:
      db_host:
        description: 'Database Host'
        required: true
        type: string
      db_port:
        description: 'Database Port'
        required: true
        type: string
        default: '5432'
      db_name:
        description: 'Database Name'
        required: true
        type: string
      db_user:
        description: 'Database User'
        required: true
        type: string
      db_password:
        description: 'Database Password'
        required: true
        type: string
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Generate database documentation
        env:
          DB_HOST: ${{ github.event.inputs.db_host }}
          DB_PORT: ${{ github.event.inputs.db_port }}
          DB_NAME: ${{ github.event.inputs.db_name }}
          DB_USER: ${{ github.event.inputs.db_user }}
          DB_PASS: ${{ github.event.inputs.db_password }}
        run: |
          mkdir -p docs/database
          echo "# Petadex Database Schema" > docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "Auto-generated on $(date)" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "Connected to: $DB_HOST:$DB_PORT/$DB_NAME" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "## Tables" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          
          # Get all table names
          TABLES=$(PGPASSWORD=$DB_PASS psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -t -c "
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE'
            ORDER BY table_name;
          " | tr -d ' ')
          
          echo "=== DEBUG: Found tables: $TABLES ==="
          
          # Generate documentation for each table
          for table in $TABLES; do
            echo "=== DEBUG: Processing table: $table ==="
            echo "### ${table^^} Table" >> docs/database/generated-schema.md
            echo "" >> docs/database/generated-schema.md
            echo "| Column | Type | Nullable | Default |" >> docs/database/generated-schema.md
            echo "|--------|------|----------|---------|" >> docs/database/generated-schema.md
            
            PGPASSWORD=$DB_PASS psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -t -c "
            SELECT 
              '| ' || column_name || ' | ' || data_type || 
              CASE WHEN character_maximum_length IS NOT NULL 
                   THEN '(' || character_maximum_length || ')' 
                   ELSE '' END || ' | ' ||
              CASE WHEN is_nullable = 'YES' THEN 'Yes' ELSE 'No' END || ' | ' ||
              COALESCE(column_default, '') || ' |'
            FROM information_schema.columns 
            WHERE table_name = '$table' 
            ORDER BY ordinal_position;
            " >> docs/database/generated-schema.md
            
            echo "" >> docs/database/generated-schema.md
          done
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-documentation
          path: docs/database/generated-schema.md