name: Generate Database Documentation

on:
  pull_request:
    paths:
      - 'backend/sql/**'
      - 'backend/src/routes/**'
      - 'backend/src/db.js'
  workflow_dispatch:

jobs:
  document-database:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: petadex
          POSTGRES_PASSWORD: dev_password  
          POSTGRES_DB: petadex_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U petadex; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          
      - name: Setup database schema
        run: |
          PGPASSWORD=dev_password psql -h localhost -U petadex -d petadex_db -f backend/sql/schema.sql
          
      - name: Generate simple schema documentation
        run: |
          echo "# Petadex Database Schema" > docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "Auto-generated on $(date)" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "## Tables" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          
          # Get table info
          PGPASSWORD=dev_password psql -h localhost -U petadex -d petadex_db -c "
          SELECT 
            '| ' || column_name || ' | ' || data_type || 
            CASE WHEN character_maximum_length IS NOT NULL 
                 THEN '(' || character_maximum_length || ')' 
                 ELSE '' END || ' | ' ||
            CASE WHEN is_nullable = 'YES' THEN 'Yes' ELSE 'No' END || ' | ' ||
            COALESCE(column_default, '') || ' |'
          FROM information_schema.columns 
          WHERE table_name = 'fastaa' 
          ORDER BY ordinal_position;
          " -t >> docs/database/generated-schema.md
          
          # Add header
          sed -i '7i### FASTAA Table\n\n| Column | Type | Nullable | Default |\n|--------|------|----------|---------|' docs/database/generated-schema.md
          
      - name: Commit generated documentation
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update database schema documentation'
          add: 'docs/database/generated-schema.md'
          default_author: github_actions
