name: Generate Database Documentation

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Load environment variables and generate documentation
        run: |
          # Source the .env file to load variables
          if [ -f backend/.env ]; then
            set -a  # automatically export all variables
            source backend/.env
            set +a  # stop automatically exporting
            echo "Loaded environment variables from backend/.env"
          else
            echo "Error: backend/.env file not found"
            exit 1
          fi
          
          mkdir -p docs/database
          echo "# Petadex Database Schema" > docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "Auto-generated on $(date)" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "Connected to: $DB_HOST:$DB_PORT/$DB_NAME" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "## Tables" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          
          # Get all table names
          TABLES=$(PGPASSWORD=$DB_PASS psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -t -c "
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE'
            ORDER BY table_name;
          " | tr -d ' ')
          
          echo "=== DEBUG: Found tables: $TABLES ==="
          
          # Generate documentation for each table
          for table in $TABLES; do
            echo "=== DEBUG: Processing table: $table ==="
            echo "### ${table^^} Table" >> docs/database/generated-schema.md
            echo "" >> docs/database/generated-schema.md
            echo "| Column | Type | Nullable | Default |" >> docs/database/generated-schema.md
            echo "|--------|------|----------|---------|" >> docs/database/generated-schema.md
            
            PGPASSWORD=$DB_PASS psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -t -c "
            SELECT 
              '| ' || column_name || ' | ' || data_type || 
              CASE WHEN character_maximum_length IS NOT NULL 
                   THEN '(' || character_maximum_length || ')' 
                   ELSE '' END || ' | ' ||
              CASE WHEN is_nullable = 'YES' THEN 'Yes' ELSE 'No' END || ' | ' ||
              COALESCE(column_default, '') || ' |'
            FROM information_schema.columns 
            WHERE table_name = '$table' 
            ORDER BY ordinal_position;
            " >> docs/database/generated-schema.md
            
            echo "" >> docs/database/generated-schema.md
          done

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-documentation
          path: docs/database/generated-schema.md