name: Generate Database Documentation

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: petadex
          POSTGRES_PASSWORD: dev_password  
          POSTGRES_DB: petadex_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U petadex; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          
      - name: Setup database schema
        run: |
          PGPASSWORD=dev_password psql -h localhost -U petadex -d petadex_db -f backend/sql/schema.sql

      - name: Generate simple schema documentation
        run: |
          mkdir -p docs/database
          echo "# Petadex Database Schema" > docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "Auto-generated on $(date)" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          echo "## Tables" >> docs/database/generated-schema.md
          echo "" >> docs/database/generated-schema.md
          
          # Get all table names and debug
          echo "=== DEBUG: Checking for tables ==="
          PGPASSWORD=dev_password psql -h localhost -U petadex -d petadex_db -c "
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE'
            ORDER BY table_name;
          "
          
          TABLES=$(PGPASSWORD=dev_password psql -h localhost -U petadex -d petadex_db -t -c "
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE'
            ORDER BY table_name;
          " | tr -d ' ')
          
          echo "=== DEBUG: Found tables: $TABLES ==="
          echo "=== DEBUG: Number of tables found: $(echo $TABLES | wc -w) ==="
          
          # Generate documentation for each table
          for table in $TABLES; do
            echo "=== DEBUG: Processing table: $table ==="
            echo "### ${table^^} Table" >> docs/database/generated-schema.md
            echo "" >> docs/database/generated-schema.md
            echo "| Column | Type | Nullable | Default |" >> docs/database/generated-schema.md
            echo "|--------|------|----------|---------|" >> docs/database/generated-schema.md
            
            PGPASSWORD=dev_password psql -h localhost -U petadex -d petadex_db -t -c "
            SELECT 
              '| ' || column_name || ' | ' || data_type || 
              CASE WHEN character_maximum_length IS NOT NULL 
                   THEN '(' || character_maximum_length || ')' 
                   ELSE '' END || ' | ' ||
              CASE WHEN is_nullable = 'YES' THEN 'Yes' ELSE 'No' END || ' | ' ||
              COALESCE(column_default, '') || ' |'
            FROM information_schema.columns 
            WHERE table_name = '$table' 
            ORDER BY ordinal_position;
            " >> docs/database/generated-schema.md
            
            echo "" >> docs/database/generated-schema.md
          done

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-documentation
          path: docs/database/generated-schema.md